language: node_js
node_js:
  - "9"

cache:
  directories:
    - node_modules

jobs:
  fast_finish: true
  allow_failures:
    - env: SOLIDITY_COVERAGE=true
    - env: SOLC_NIGHTLY=true
  include:
    # Run the unit test suite three times in parallel.
    # The first one gets results faster and is the only one required to pass.
    # The second one generates the coverage report.
    # The third one is to keep us informed about possible issues with the
    # upcoming solidity release.
    - stage: tests
      name: "unit tests"
      script: npm run test
    - stage: tests
      name: "unit tests with solc nightly"
      script: npm run test
      env: SOLC_NIGHTLY=true
after_script:
  npm run coverage && cat coverage/lcov.info | coveralls